// @ts-nocheck
import { useCallback, useEffect, useState } from 'react';
import { Navigate, Routes, Route, Link, useNavigate } from 'react-router-dom';
import { supabase } from '../lib/supabase';
import type { Project, ProjectImage, Skill } from '../types/content';
import { LogOut, Plus, Trash2, ExternalLink, ImagePlus } from 'lucide-react';

type Tab = 'overview' | 'projects' | 'skills' | 'about' | 'resume' | 'contacts' | 'settings';
const tabs: Tab[] = ['overview', 'projects', 'skills', 'about', 'resume', 'contacts', 'settings'];

function safeStorageFilename(filename: string) {
  const lastDot = filename.lastIndexOf('.');
  const basename = lastDot > 0 ? filename.slice(0, lastDot) : filename;
  const extension = lastDot > 0 ? filename.slice(lastDot + 1) : '';
  const safeBasename = basename.normalize('NFKD').replace(/[\u0300-\u036f]/g, '').toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-+|-+$/g, '').slice(0, 80) || 'file';
  const safeExtension = extension.toLowerCase().replace(/[^a-z0-9]/g, '').slice(0, 20);
  return safeExtension ? `${safeBasename}.${safeExtension}` : safeBasename;
}

function Login() { const [email, setEmail] = useState(''); const [password, setPassword] = useState(''); const [error, setError] = useState(''); const nav = useNavigate(); async function go(e: React.FormEvent) { e.preventDefault(); if (!supabase) return setError('Configure Supabase environment variables to enable administration.'); const { error } = await supabase.auth.signInWithPassword({ email, password }); if (error) setError(error.message); else nav('/admin'); } return <main className="login"><Link to="/" className="brand">OF<span>·</span></Link><h1>Portfolio administration</h1><p>Sign in with an administrator account.</p><form onSubmit={go}><input placeholder="Email" type="email" required value={email} onChange={e => setEmail(e.target.value)} /><input placeholder="Password" type="password" required value={password} onChange={e => setPassword(e.target.value)} /><button className="button primary">Sign in</button>{error && <p className="error">{error}</p>}</form></main>; }

function Crud<T extends { id: string; [key: string]: unknown }>({ table, title, fields, starter }: { table: string; title: string; fields: string[]; starter: Record<string, unknown> }) {
  const [items, setItems] = useState<T[]>([]); const [editing, setEditing] = useState<Partial<T> | null>(null); const [loading, setLoading] = useState(true);
  const load = useCallback(async () => { if (!supabase) return; setLoading(true); const { data, error } = await supabase.from(table).select('*').order('display_order'); if (!error) setItems((data || []) as T[]); setLoading(false); }, [table]);
  useEffect(() => { let active = true; setItems([]); setEditing(null); setLoading(true); supabase?.from(table).select('*').order('display_order').then(({ data, error }) => { if (active) { if (!error) setItems((data || []) as T[]); setLoading(false); } }); return () => { active = false; }; }, [table]);
  async function save(e: React.FormEvent<HTMLFormElement>) { e.preventDefault(); if (!supabase || !editing) return; const f = new FormData(e.currentTarget); const values = Object.fromEntries(fields.map(k => [k, k === 'published' || k === 'featured' ? f.get(k) === 'on' : k === 'display_order' ? Number(f.get(k) || 0) : k === 'categories' || k === 'technologies' ? String(f.get(k) || '').split(',').map(x => x.trim()).filter(Boolean) : k === 'key_features' ? String(f.get(k) || '').split(/\r?\n/).map(x => x.trim()).filter(Boolean) : f.get(k) || null])); const { error } = editing.id ? await supabase.from(table).update(values).eq('id', editing.id) : await supabase.from(table).insert(values); if (error) alert(error.message); else { setEditing(null); load(); } }
  return <section className="admin-panel"><div className="panel-head"><div><p className="eyebrow">MANAGE</p><h1>{title}</h1></div><button className="button primary" onClick={() => setEditing(starter)}><Plus /> Add {title.slice(0, -1)}</button></div>{editing && <form className="editor" onSubmit={save}><h2>{editing.id ? 'Edit' : 'New'} {title.slice(0, -1)}</h2>{fields.map(k => <label key={k}>{k.replaceAll('_', ' ')}{k === 'published' || k === 'featured' ? <input type="checkbox" name={k} defaultChecked={Boolean(editing[k])} /> : k === 'key_features' ? <textarea name={k} defaultValue={Array.isArray(editing[k]) ? editing[k].join('\n') : String(editing[k] || '')} /> : k.includes('description') || ['full_description', 'problem', 'solution', 'how_it_works', 'contribution'].includes(k) ? <textarea name={k} defaultValue={String(editing[k] || '')} /> : <input name={k} type={k === 'display_order' ? 'number' : 'text'} defaultValue={String(editing[k] || '')} />}</label>)}<button className="button primary">Save</button><button type="button" className="button" onClick={() => setEditing(null)}>Cancel</button></form>}<div className="admin-list">{loading ? <p className="empty">Loading {title.toLowerCase()}…</p> : items.map(i => <article key={i.id}><div><h3>{String(i.title || i.name)}</h3><p>{String(i.short_description || i.category || '')}</p></div><span>{i.published ? 'Published' : 'Draft'}</span><button onClick={() => setEditing(i)}>Edit</button><button aria-label="Delete" onClick={async () => { if (confirm('Delete this item?')) { await supabase?.from(table).delete().eq('id', i.id); load(); } }}><Trash2 /></button></article>)}</div></section>;
}

type UploadedFile = { publicUrl: string; storagePath: string };

function ProjectEditor({ upload }: { upload: (file: File, bucket: string, directory?: string) => Promise<UploadedFile | undefined> }) {
  const [projects, setProjects] = useState<Project[]>([]); const [editing, setEditing] = useState<Partial<Project> | null>(null); const [images, setImages] = useState<ProjectImage[]>([]); const [loading, setLoading] = useState(true);
  const load = useCallback(async () => { if (!supabase) return; setLoading(true); const { data } = await supabase.from('projects').select('*').order('display_order'); setProjects((data || []) as Project[]); setLoading(false); }, []);
  const loadImages = useCallback(async (projectId: string) => { if (!supabase) return; const { data, error } = await supabase.from('project_images').select('*').eq('project_id', projectId).order('display_order'); if (!error) setImages((data || []) as ProjectImage[]); }, []);
  useEffect(() => { load(); }, [load]);
  useEffect(() => { if (editing?.id) loadImages(editing.id); else setImages([]); }, [editing?.id, loadImages]);
  function begin(project: Partial<Project>) { setImages([]); setEditing(project); }
  async function save(e: React.FormEvent<HTMLFormElement>) { e.preventDefault(); if (!supabase || !editing) return; const f = new FormData(e.currentTarget); const fields = ['title', 'slug', 'short_description', 'full_description', 'thumbnail_url', 'categories', 'technologies', 'github_url', 'live_url', 'project_date', 'featured', 'published', 'display_order', 'problem', 'solution', 'how_it_works', 'key_features', 'contribution']; const values = Object.fromEntries(fields.map(k => [k, k === 'published' || k === 'featured' ? f.get(k) === 'on' : k === 'display_order' ? Number(f.get(k) || 0) : k === 'categories' || k === 'technologies' ? String(f.get(k) || '').split(',').map(x => x.trim()).filter(Boolean) : k === 'key_features' ? String(f.get(k) || '').split(/\r?\n/).map(x => x.trim()).filter(Boolean) : f.get(k) || null])); const result = editing.id ? await supabase.from('projects').update(values).eq('id', editing.id).select().single() : await supabase.from('projects').insert(values).select().single(); if (result.error) return alert(result.error.message); await load(); begin(result.data as Project); }
  async function addImages(files: FileList | null) { if (!files || !editing?.id) return; for (const file of Array.from(files)) { if (!file.type.startsWith('image/')) { alert(`${file.name} is not an image.`); continue; } const uploaded = await upload(file, 'project-images', `projects/${editing.id}`); if (!uploaded) continue; const { error } = await supabase!.from('project_images').insert({ project_id: editing.id, storage_path: uploaded.storagePath, alt_text: file.name.replace(/\.[^.]+$/, ''), display_order: images.length }); if (error) alert(error.message); } loadImages(editing.id); }
  async function removeImage(image: ProjectImage) { if (!supabase || !confirm('Remove this project image?')) return; const { error } = await supabase.from('project_images').delete().eq('id', image.id); if (error) return alert(error.message); if (image.storage_path && !image.storage_path.startsWith('http')) await supabase.storage.from('project-images').remove([image.storage_path]); loadImages(editing!.id!); }
  const fields = ['title', 'slug', 'short_description', 'full_description', 'thumbnail_url', 'categories', 'technologies', 'github_url', 'live_url', 'project_date', 'featured', 'published', 'display_order', 'problem', 'solution', 'how_it_works', 'key_features', 'contribution'];
  return <section className="admin-panel"><div className="panel-head"><div><p className="eyebrow">MANAGE</p><h1>Projects</h1></div><button className="button primary" onClick={() => begin({ featured: false, published: false, display_order: 0, categories: [], technologies: [], key_features: [] })}><Plus /> Add Project</button></div>{editing && <form className="editor" onSubmit={save}><h2>{editing.id ? 'Edit' : 'New'} Project</h2>{fields.map(k => <label key={k}>{k.replaceAll('_', ' ')}{k === 'published' || k === 'featured' ? <input type="checkbox" name={k} defaultChecked={Boolean(editing[k])} /> : k === 'key_features' ? <textarea name={k} defaultValue={Array.isArray(editing[k]) ? editing[k].join('\n') : String(editing[k] || '')} /> : k.includes('description') || ['full_description', 'problem', 'solution', 'how_it_works', 'contribution'].includes(k) ? <textarea name={k} defaultValue={String(editing[k] || '')} /> : <input name={k} type={k === 'display_order' ? 'number' : 'text'} defaultValue={Array.isArray(editing[k]) ? editing[k].join(', ') : String(editing[k] || '')} />}</label>)}<div className="project-gallery"><div><p className="eyebrow">PROJECT GALLERY</p><h3>Images</h3><p className="empty">Save the project first, then add one or more images. Images are optional.</p></div>{editing.id ? <label className="button gallery-upload"><ImagePlus /> Add images<input type="file" accept="image/jpeg,image/png,image/webp" multiple onChange={e => { addImages(e.target.files); e.currentTarget.value = ''; }} /></label> : <p className="empty">Available after the first save.</p>}<div className="gallery-grid">{images.map(image => <figure key={image.id}><img src={image.storage_path.startsWith('http') ? image.storage_path : supabase!.storage.from('project-images').getPublicUrl(image.storage_path).data.publicUrl} alt={image.alt_text || ''} /><figcaption>{image.alt_text || 'Project image'}<button type="button" aria-label="Remove image" onClick={() => removeImage(image)}><Trash2 /></button></figcaption></figure>)}</div></div><button className="button primary">Save project</button><button type="button" className="button" onClick={() => setEditing(null)}>Cancel</button></form>}<div className="admin-list">{loading ? <p className="empty">Loading projects…</p> : projects.map(project => <article key={project.id}><div><h3>{project.title}</h3><p>{project.short_description}</p></div><span>{project.published ? 'Published' : 'Draft'}</span><button onClick={() => begin(project)}>Edit</button><button aria-label="Delete" onClick={async () => { if (confirm('Delete this project?')) { await supabase?.from('projects').delete().eq('id', project.id); load(); } }}><Trash2 /></button></article>)}</div></section>;
}

function Dashboard() { const [tab, setTab] = useState<Tab>('overview'); const [user, setUser] = useState(''); useEffect(() => { supabase?.auth.getUser().then(({ data }) => setUser(data.user?.email || '')); }, []); async function upload(file: File, bucket: string, directory = 'uploads'): Promise<UploadedFile | undefined> { const storagePath = `${directory}/${crypto.randomUUID()}-${safeStorageFilename(file.name)}`; const { error } = await supabase!.storage.from(bucket).upload(storagePath, file); if (error) { alert(error.message); return; } return { storagePath, publicUrl: supabase!.storage.from(bucket).getPublicUrl(storagePath).data.publicUrl }; } return <div className="admin"><aside><Link className="brand" to="/">OF<span>·</span></Link><p>{user}</p>{tabs.map(x => <button key={x} className={tab === x ? 'selected' : ''} onClick={() => setTab(x)}>{x}</button>)}<button onClick={() => supabase?.auth.signOut()}><LogOut /> Sign out</button></aside><main>{tab === 'overview' && <Overview />}{tab === 'projects' && <ProjectEditor key="projects" upload={upload} />}{tab === 'skills' && <Crud<Skill> key="skills" table="skills" title="Skills" starter={{ published: false, display_order: 0 }} fields={['name', 'category', 'description', 'icon', 'published', 'display_order']} />}{tab === 'about' && <ContentEditor />}{tab === 'resume' && <Resume upload={upload} />}{tab === 'contacts' && <Contacts />}{tab === 'settings' && <Settings />}</main></div>; }
function Overview() { return <section className="admin-panel"><p className="eyebrow">DASHBOARD</p><h1>Welcome back.</h1><p>Manage published portfolio content, incoming enquiries and your active resume from one private workspace.</p><div className="notice">Only authenticated users approved by the database’s <code>is_admin()</code> policy can make changes.</div></section>; }
function ContentEditor() { const [body, setBody] = useState(''); useEffect(() => { supabase?.from('site_content').select('content').eq('key', 'about').single().then(({ data }) => setBody(data?.content?.body || '')); }, []); return <section className="admin-panel"><h1>About content</h1><form onSubmit={async e => { e.preventDefault(); await supabase?.from('site_content').upsert({ key: 'about', content: { body }, published: true }); alert('Saved'); }}><textarea rows={14} value={body} onChange={e => setBody(e.target.value)} placeholder="Edit your professional About section…" /><button className="button primary">Save About</button></form></section>; }
function Resume({ upload }: { upload: (f: File, b: string) => Promise<UploadedFile | undefined> }) { const [url, setUrl] = useState(''); async function submit(e: React.FormEvent<HTMLFormElement>) { e.preventDefault(); const f = (e.currentTarget.elements.namedItem('resume') as HTMLInputElement).files?.[0]; if (!f || f.type !== 'application/pdf') return alert('Please select a PDF.'); const uploaded = await upload(f, 'resumes'); if (uploaded) { await supabase?.from('site_settings').upsert({ key: 'resume_url', value: uploaded.publicUrl }); setUrl(uploaded.publicUrl); } } return <section className="admin-panel"><h1>Resume</h1><p>Upload a PDF to replace the public Download Resume link.</p><form onSubmit={submit}><input name="resume" type="file" accept="application/pdf" required /><button className="button primary">Upload & publish</button></form>{url && <a href={url} target="_blank">View current resume <ExternalLink /></a>}</section>; }
function Contacts() { const [items, setItems] = useState<{ id: string; name: string; email: string; message: string; status: string; created_at: string }[]>([]); useEffect(() => { supabase?.from('contact_submissions').select('*').order('created_at', { ascending: false }).then(({ data }) => setItems(data || [])); }, []); return <section className="admin-panel"><h1>Contact submissions</h1><div className="admin-list">{items.map(x => <article key={x.id}><div><h3>{x.name} · {x.email}</h3><p>{x.message}</p><small>{new Date(x.created_at).toLocaleDateString()}</small></div><span>{x.status}</span></article>)}</div></section>; }
function Settings() { const [rows, setRows] = useState<{ key: string; value: string }[]>([]); useEffect(() => { supabase?.from('site_settings').select('*').then(({ data }) => setRows((data || []) as { key: string; value: string }[])); }, []); return <section className="admin-panel"><h1>Site settings & social links</h1><p>Use key/value entries for public contact details and links, such as <code>github_url</code>, <code>linkedin_url</code> or <code>contact_email</code>.</p><form onSubmit={async e => { e.preventDefault(); const f = new FormData(e.currentTarget); await supabase?.from('site_settings').upsert({ key: f.get('key'), value: f.get('value') }); location.reload(); }}><input name="key" placeholder="Setting key" /><input name="value" placeholder="Value" /><button className="button primary">Save setting</button></form>{rows.length > 0 && <p className="empty">{rows.length} saved setting{rows.length === 1 ? '' : 's'}.</p>}</section>; }
export default function Admin() { const [ready, setReady] = useState(false), [authed, setAuthed] = useState(false); useEffect(() => { if (!supabase) return setReady(true); supabase.auth.getSession().then(({ data }) => { setAuthed(Boolean(data.session)); setReady(true); }); return supabase.auth.onAuthStateChange((_, s) => setAuthed(Boolean(s))).data.subscription.unsubscribe; }, []); if (!ready) return null; if (!supabase) return <Login />; return <Routes><Route path="login" element={authed ? <Navigate to="/admin" /> : <Login />} /><Route path="*" element={authed ? <Dashboard /> : <Navigate to="/admin/login" />} /></Routes>; }
